# Generated by Django 3.0.4 on 2020-03-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iprocarlo_app', '0002_filter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='Filters',
        ),
        migrations.AlterModelOptions(
            name='filters',
            options={'verbose_name_plural': 'Filters'},
        ),
    ]
