# Generated by Django 3.0.4 on 2020-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprocarlo_app', '0004_auto_20200326_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_date',
            field=models.DateTimeField(verbose_name='date searched'),
        ),
    ]
