# Generated by Django 3.0.4 on 2020-03-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iprocarlo_app', '0005_auto_20200326_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='searched',
        ),
        migrations.AddField(
            model_name='search',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iprocarlo_app.Filter'),
        ),
    ]
