# Generated by Django 3.0.4 on 2020-03-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iprocarlo_app', '0008_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
