# Generated by Django 3.0.4 on 2020-03-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iprocarlo_app', '0010_auto_20200330_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AddField(
            model_name='search',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iprocarlo_app.Filter'),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
