# Generated by Django 3.0.4 on 2020-03-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprocarlo_app', '0016_auto_20200331_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
